Repository whatssub/whatssub-mobile, pull requests merged in 2019-06, with the labels that each got.

#1 React native0.60 rc.1
  .gitignore
  README.md
  android/app/build.gradle
  android/app/debug.keystore
  android/app/proguard-rules.pro
  android/app/src/main/java/com/whatssub/MainApplication.java
  android/app/src/main/res/drawable-hdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/app/src/main/res/drawable-mdpi/assets_icons_mask.png
  android/app/src/main/res/drawable-mdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/app/src/main/res/drawable-mdpi/node_modules_reactnavigationstack_lib_module_views_assets_backiconmask.png
  android/app/src/main/res/drawable-xhdpi/assets_icons_mask.png
  android/app/src/main/res/drawable-xhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/app/src/main/res/drawable-xxhdpi/assets_icons_mask.png
  android/app/src/main/res/drawable-xxhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/app/src/main/res/drawable-xxxhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/app/src/main/res/raw/node_modules_csscolorkeywords_colors.json
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/drawable-hdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/drawable-mdpi/assets_icons_mask.png
  android/drawable-mdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/drawable-mdpi/node_modules_reactnavigationstack_lib_module_views_assets_backiconmask.png
  android/drawable-xhdpi/assets_icons_mask.png
  android/drawable-xhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/drawable-xxhdpi/assets_icons_mask.png
  android/drawable-xxhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/drawable-xxxhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/keystores/BUCK
  android/keystores/debug.keystore.properties
  android/raw/node_modules_csscolorkeywords_colors.json
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/whatssub-tvOS/Info.plist
  ios/whatssub.xcodeproj/project.pbxproj
  ios/whatssub.xcworkspace/contents.xcworkspacedata
  ios/whatssub.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/whatssub/Info.plist
  package.json
  src/components/screen/__tests__/__snapshots__/Intro.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  src/utils/Styles.ts
  yarn.lock
Labels: upgrade

#2 Bots
  .all-contributorsrc
  .github/stale.yml
  CONTRIBUTING.md
  README.md
  package.json
  yarn.lock
Labels: bot, documentation

#3 Initial setup
  .env.sample
  .gitignore
  CONTRIBUTING.md
  README.md
  STRINGS.ts
  assets/icons/facebook.png
  assets/icons/facebook@2x.png
  assets/icons/facebook@3x.png
  assets/icons/google.png
  assets/icons/google@2x.png
  assets/icons/google@3x.png
  assets/icons/logo.png
  assets/icons/logo@2x.png
  assets/icons/logo@3x.png
  assets/icons/mask.png
  assets/icons/mask@2x.png
  assets/icons/mask@3x.png
  assets/icons/slash.png
  assets/icons/slash@2x.png
  assets/icons/slash@3x.png
  index.js
  ios/Podfile.lock
  jest.config.js
  package.json
  src/App.tsx
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/Intro.tsx
  src/components/screen/Main.tsx
  src/components/screen/Temp.tsx
  src/components/screen/__tests__/Intro.test.tsx
  src/components/screen/__tests__/Main.test.tsx
  src/components/screen/__tests__/__snapshots__/Intro.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Main.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/shared/Button.tsx
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  src/hooks/useInterval.ts
  src/providers/AppProvider.tsx
  src/styled.d.ts
  src/theme.ts
  src/utils/Icons.ts
  yarn.lock
Labels: enhancement, setup, test

#4 App config
  .circleci/config.yml
  .env.sample
  .gitignore
  CONTRIBUTING.md
  README.md
  STRINGS.ts
  android/app/src/main/java/com/whatssub/MainActivity.java
  android/app/src/main/java/com/whatssub/MainApplication.java
  config.sample.ts
  package.json
  src/App.tsx
  src/components/screen/Intro.tsx
  src/components/screen/__tests__/__snapshots__/Intro.test.tsx.snap
Labels: documentation, enhancement, setup

#9 Intro orientation screen
  src/components/screen/Intro.tsx
  src/components/screen/__tests__/__snapshots__/Intro.test.tsx.snap
Labels: orientation

#10 Improve docs
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  app.json
  clabot/.clabot
Labels: cla, docs

#11 Remove ios android gitignore
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: docs, enhancement

#13 Improve configs and remove decorator plugin for babel
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  babel.config.js
  package.json
  test/jestSetup.ts
Labels: config, docs

#12 Improve contributing doc
  CONTRIBUTING.md
Labels: docs

#17 Added app icon and splash screen
  app.json
  assets/icon.png
  assets/splash.gif
  assets/splash.png
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/AuthLoading.tsx
  src/components/screen/__tests__/AuthLoading.test.tsx
  src/components/screen/__tests__/__snapshots__/AuthLoading.test.tsx.snap
  src/utils/Images.ts
Labels: feature, milestone
