Repository whatssub/whatssub-mobile, pull requests merged in 2019-08, with the labels that each got.

#68 Upgrade expo to sdk 34
  package.json
  src/components/screen/Intro.tsx
  src/components/screen/__tests__/Intro.test.tsx
  yarn.lock
Labels: upgrade

#69 Implement [HomeTabNavigator]
  src/components/navigation/HomeTabNavigator.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/Home.tsx
  src/components/screen/HomeCalendar.tsx
  src/components/screen/HomeFavorite.tsx
  src/components/screen/HomeSetting.tsx
  src/components/screen/__tests__/Home.test.tsx
  src/components/screen/__tests__/HomeCalendar.test.tsx
  src/components/screen/__tests__/HomeFavorite.test.tsx
  src/components/screen/__tests__/HomeSetting.test.tsx
  src/components/screen/__tests__/__snapshots__/Home.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/HomeCalendar.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/HomeFavorite.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/HomeSetting.test.tsx.snap
  src/components/shared/TabBarIcon.tsx
  src/components/shared/__tests__/TabBarIcon.test.tsx
  src/components/shared/__tests__/__snapshots__/TabBarIcon.test.tsx.snap
Labels: feature, milestone

#74 Migrate/button setting
  .favorites.json
  .gitignore
  STRINGS.ts
  package.json
  src/components/screen/ExamplePieChartMonth.tsx
  src/components/screen/Intro.tsx
  src/components/screen/Setting.tsx
  src/components/screen/Temp.tsx
  src/components/screen/__tests__/__snapshots__/Setting.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/shared/Button.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  storybook/stories/index.js
  storybook/stories/shared/Button.js
  yarn.lock
Labels: enhancement, migration

#77 Fixed readme on changed repo
  .github/FUNDING.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package.json
Labels: docs

#78 Add more stories and doc
  .gitignore
  App.tsx
  CONTRIBUTING.md
  STORYBOOK.md
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/__tests__/ExamplePieChartMonth.test.tsx
  src/components/screen/__tests__/__snapshots__/ExamplePieChartMonth.test.tsx.snap
  src/components/shared/__tests__/PieChart.test.tsx
  src/components/shared/__tests__/__snapshots__/PieChart.test.tsx.snap
  storybook/stories/index.js
  storybook/stories/shared/PieChart.js
  storybook/stories/shared/ProductCard.js
  storybook/stories/shared/SectionList.js
  storybook/stories/shared/index.js
  storybook/utils/FakeNavigator.js
Labels: enhancement

#39 Integrate apollo client to whatssub-dev server
  package.json
  src/App.tsx
  src/apis/sample.ts
  src/apis/urls.ts
  src/apollo/Client.ts
  src/apollo/LocalState.ts
  src/apollo/testClient.ts
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/AuthLoading.tsx
  src/components/screen/Intro.tsx
  src/components/screen/Temp.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/screen/__tests__/__snapshots__/Setting.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/PieChart.test.tsx.snap
  src/theme.ts
  src/types/index.ts
  src/utils/_testUtils.ts
  yarn.lock
Labels: feature, milestone

#80 Fix ProductCard component snapshot bug
  .eslintrc.js
  src/components/shared/ProductCard.tsx
  src/components/shared/__tests__/ProductCard.test.tsx
  src/components/shared/__tests__/__snapshots__/ProductCard.test.tsx.snap
Labels: bugfix

#81 Update eslint rules
  .eslintrc.js
  src/App.tsx
  src/components/navigation/HomeTabNavigator.tsx
  src/components/screen/AuthLoading.tsx
  src/components/screen/CustomSubsRegister.tsx
  src/components/shared/ProductCard.tsx
  src/components/shared/ServiceHeader.tsx
  src/components/shared/__tests__/TabBarIcon.test.tsx
  src/components/shared/__tests__/__snapshots__/DatePicker.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/ProductCard.test.tsx.snap
  src/providers/__tests__/AppProvider.test.tsx
  src/types/index.ts
  storybook/stories/shared/ProductCard.js
Labels: enhancement, lint
