Repository whatssub/whatssub-mobile, pull requests merged in 2019-07, with the labels that each got.

#23 installing babel-plugin-styled-components and lodash
  STRINGS.ts
  babel.config.js
  jest.config.js
  package.json
  src/components/screen/Intro.tsx
  src/components/screen/__tests__/Intro.test.tsx
  src/components/screen/__tests__/__snapshots__/Intro.test.tsx.snap
  yarn.lock
Labels: enhancement

#20 Implement Facebook sign in
  README.md
  __mocks__/expo-facebook.ts
  __mocks__/firebase.ts
  __mocks__/react-firebase-hooks/auth.ts
  config.sample.ts
  src/components/screen/Intro.tsx
  src/components/screen/__tests__/Intro.test.tsx
Labels: feature, milestone

#27 Remove firebase
  CONTRIBUTING.md
  README.md
  __mocks__/expo-facebook.ts
  __mocks__/firebase.ts
  __mocks__/react-firebase-hooks/auth.ts
  config.sample.ts
  jest.config.js
  package.json
  src/App.tsx
  src/components/screen/Intro.tsx
  src/components/screen/__tests__/Intro.test.tsx
  yarn.lock
Labels: enhancement, migration

#22 Implement Google Signin
  .gitignore
  README.md
  __mocks__/GoogleSignIn.ts
  app.json
  app.sample.json
  config.sample.ts
  package.json
  src/components/screen/Intro.tsx
  src/components/screen/__tests__/Intro.test.tsx
Labels: feature, milestone

#28 fix strange text-align in Introscreen
  src/components/screen/Intro.tsx
Labels: enhancement

#30 Migrated to testing-library and manifest organized variables
  .gitignore
  README.md
  app.sample.json
  assets/icon.png
  assets/icons/facebook.png
  assets/icons/facebook@2x.png
  assets/icons/facebook@3x.png
  assets/icons/google.png
  assets/icons/google@2x.png
  assets/icons/google@3x.png
  assets/icons/logo.png
  assets/icons/logo@2x.png
  assets/icons/logo@3x.png
  assets/icons/slash.png
  assets/icons/slash@2x.png
  assets/icons/slash@3x.png
  config.sample.ts
  package.json
  src/components/screen/Intro.tsx
  src/components/screen/__tests__/Intro.test.tsx
  src/components/screen/__tests__/Main.test.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/shared/Button.tsx
  yarn.lock
Labels: migration

#31 Improve [GoogleSignIn] testing
  src/components/screen/__tests__/Intro.test.tsx
Labels: enhancement

#36 enhance:google signin test
  __mocks__/GoogleSignIn.ts
  __mocks__/expo-google-sign-in.ts
  package.json
  src/components/screen/__tests__/Intro.test.tsx
Labels: enhancement

#41 Enhance/oauth
  README.md
  config.sample.ts
  src/apis/sample.ts
  src/components/screen/Intro.tsx
  src/components/screen/__tests__/Intro.test.tsx
Labels: enhancement

#42 Add client id for expo android
  README.md
  config.sample.ts
  src/components/screen/Intro.tsx
Labels: enhancement

#40 Add ProductCard Component
  .gitignore
  STRINGS.ts
  assets/fonts/SpocaHanSans/SpoqaHanSans-Bold.ttf
  assets/fonts/SpocaHanSans/SpoqaHanSans-Regular.ttf
  assets/icons/alarmOff.png
  assets/icons/alarmOff@2x.png
  assets/icons/alarmOff@3x.png
  assets/icons/alarmOn.png
  assets/icons/alarmOn@2x.png
  assets/icons/alarmOn@3x.png
  assets/icons/edit.png
  assets/icons/edit@2x.png
  assets/icons/edit@3x.png
  assets/icons/noti_off.png
  assets/icons/noti_on.png
  assets/icons/setting.png
  package.json
  src/App.tsx
  src/components/shared/ProductCard.tsx
  src/components/shared/TempProductCard.tsx
  src/components/shared/__tests__/ProductCard.test.tsx
  src/components/shared/__tests__/__snapshots__/ProductCard.test.tsx.snap
  src/utils/Icons.ts
  src/utils/Images.ts
  yarn.lock
Labels: feature

#38 Implement PieChart
  STRINGS.ts
  package.json
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/ExamplePieChartMonth.tsx
  src/components/screen/__tests__/ExamplePieChartMonth.test.tsx
  src/components/screen/__tests__/__snapshots__/ExamplePieChartMonth.test.tsx.snap
  src/components/shared/PieChart.tsx
  src/components/shared/__tests__/PieChart.test.tsx
  src/components/shared/__tests__/__snapshots__/PieChart.test.tsx.snap
  yarn.lock
Labels: feature, milestone

#53 Enhance linting rules
  .eslintrc.js
  package.json
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/AuthLoading.tsx
  src/components/screen/ExamplePieChartMonth.tsx
  src/components/screen/Intro.tsx
  src/components/screen/Main.tsx
  src/components/screen/MainEmpty.tsx
  src/components/screen/Temp.tsx
  src/components/shared/Button.tsx
  src/components/shared/PieChart.tsx
  src/components/shared/ProductCard.tsx
  src/components/shared/TempProductCard.tsx
  src/providers/AppProvider.tsx
  yarn.lock
Labels: enhancement, lint

#54 Enhanced linting2
  .circleci/config.yml
  package.json
  src/App.tsx
  src/apis/sample.ts
  src/components/screen/__tests__/AuthLoading.test.tsx
  src/components/screen/__tests__/ExamplePieChartMonth.test.tsx
  src/components/screen/__tests__/Intro.test.tsx
  src/components/screen/__tests__/Main.test.tsx
  src/components/screen/__tests__/MainEmpty.test.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/PieChart.test.tsx
  src/components/shared/__tests__/ProductCard.test.tsx
  src/providers/AppProvider.tsx
  src/theme.ts
  src/types/index.ts
  src/utils/Images.ts
  src/utils/Styles.ts
  types/index.ts
Labels: lint

#44 Feature/storybook
  .circleci/config.yml
  .favorites.json
  .gitignore
  App.tsx
  package.json
  storybook/addons.js
  storybook/decorators.js
  storybook/index.js
  storybook/rn-addons.js
  storybook/stories/AuthLoading.js
  storybook/stories/index.js
  storybook/stories/sample/Button/index.android.js
  storybook/stories/sample/Button/index.ios.js
  storybook/stories/sample/CenterView/index.js
  storybook/stories/sample/CenterView/style.js
  storybook/stories/sample/Welcome/index.js
  storybook/stories/sample/index.js
  storybook/stories/shared/Button.js
  tsconfig.json
  yarn.lock
Labels: enhancement

#43 Added test code for splash screen
  src/components/screen/AuthLoading.tsx
  src/components/screen/__tests__/AuthLoading.test.tsx
Labels: enhancement, test

#56 Enhanced default theming and handle it permanently
  src/App.tsx
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/AuthLoading.tsx
  src/components/screen/ExamplePieChartMonth.tsx
  src/components/screen/Intro.tsx
  src/components/screen/Temp.tsx
  src/components/screen/__tests__/AuthLoading.test.tsx
  src/components/screen/__tests__/ExamplePieChartMonth.test.tsx
  src/components/screen/__tests__/Intro.test.tsx
  src/components/screen/__tests__/MainEmpty.test.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/screen/__tests__/__snapshots__/AuthLoading.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/ExamplePieChartMonth.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/shared/Button.tsx
  src/components/shared/PieChart.tsx
  src/components/shared/ProductCard.tsx
  src/components/shared/TempProductCard.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/PieChart.test.tsx
  src/components/shared/__tests__/ProductCard.test.tsx
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  src/providers/AppProvider.tsx
  src/styled.d.ts
  src/theme.ts
  src/types/index.ts
  types/index.ts
Labels: enhancement

#60 Add eslint import order rule
  .eslintrc.js
  src/App.tsx
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/AuthLoading.tsx
  src/components/screen/ExamplePieChartMonth.tsx
  src/components/screen/Intro.tsx
  src/components/screen/Main.tsx
  src/components/screen/MainEmpty.tsx
  src/components/screen/Temp.tsx
  src/components/screen/__tests__/AuthLoading.test.tsx
  src/components/screen/__tests__/ExamplePieChartMonth.test.tsx
  src/components/screen/__tests__/Intro.test.tsx
  src/components/screen/__tests__/Main.test.tsx
  src/components/screen/__tests__/MainEmpty.test.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/shared/Button.tsx
  src/components/shared/PieChart.tsx
  src/components/shared/ProductCard.tsx
  src/components/shared/TempProductCard.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/PieChart.test.tsx
  src/components/shared/__tests__/ProductCard.test.tsx
  src/components/ui/Buttons.ts
  src/providers/AppProvider.tsx
  src/providers/index.ts
Labels: enhancement, lint

#62 Refactor providers for readability and reusability
  package.json
  src/App.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/Intro.tsx
  src/components/screen/__tests__/Intro.test.tsx
  src/contexts/index.ts
  src/providers/AppProvider.tsx
  src/providers/StyledComponentThemeProvider.tsx
  src/providers/__tests__/AppProvider.test.tsx
  src/providers/__tests__/__snapshots__/AppProvider.test.tsx.snap
  src/providers/index.ts
  src/providers/index.tsx
  storybook/decorators.js
  storybook/index.js
  storybook/stories/index.js
  storybook/stories/sample/Button/index.android.js
  storybook/stories/sample/Button/index.ios.js
  storybook/stories/sample/CenterView/index.js
  storybook/stories/sample/Welcome/index.js
  storybook/stories/sample/index.js
  storybook/stories/screen/AuthLoading.js
  storybook/stories/screen/index.js
  storybook/stories/shared/Button.js
Labels: enhancement

#64 Migrate/switch toggle
  .circleci/config.yml
  babel.config.js
  jest.config.js
  package.json
  src/components/screen/TempProductCard.tsx
  src/components/shared/ProductCard.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement, migration

#65 Implement screen [Setting] with shared components.
  STRINGS.ts
  package.json
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/Setting.tsx
  src/components/screen/__tests__/Setting.test.tsx
  src/components/screen/__tests__/__snapshots__/Setting.test.tsx.snap
  src/components/shared/SectionList.tsx
  src/components/shared/SettingOption.tsx
  src/components/shared/SwitchToggle.tsx
  src/components/shared/__tests__/SectionList.test.tsx
  src/components/shared/__tests__/SettingOption.test.tsx
  src/components/shared/__tests__/SwitchToggle.test.tsx
  src/components/shared/__tests__/__snapshots__/SectionList.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/SettingOption.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/SwitchToggle.test.tsx.snap
  yarn.lock
Labels: feature, milestone

#67 Installed dooboo-native-widgets
  package.json
  src/components/shared/SwitchToggle.tsx
  src/components/shared/__tests__/SwitchToggle.test.tsx
  yarn.lock
Labels: enhancement, migration
